// <auto-generated />
namespace kanbanBoard_aspdotnetmvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deleteState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteState));
        
        string IMigrationMetadata.Id
        {
            get { return "202208180851048_deleteState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
